version: "3.4"
 
services:
 
  socket_php:
    image: requix/custom-php:version-1.0.0
    hostname: "socket-php"
    working_dir: "/var/www/html"
    volumes:
      - "..:/var/www/html"
      - "../docker/socket:/socket"
 
  socket_nginx:
    image: requix/custom-nginx:version-1.0.0
    hostname: "socket-nginx"
    working_dir: "/var/www/html"
    ports:
      - "6080:8080"
    volumes:
      - "..:/var/www/html"
      - "../docker/socket:/socket"
